services:
  latex:
    container_name: LaTeX
    tty: true
    restart: always
    env_file:
      - .env.dir
    environment:
      - TZ=Asia/Tokyo
      - LANG=C
    build:
      args:
        t2p: "/usr/local/bin/"
        dir: "documents"
        lang: "C"
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./${VOLDIR}:/home/${WORKDIR}/documents
    working_dir: /home/${WORKDIR}