services:
  latex:
    container_name: LaTeX
    tty: true
    restart: always
    build:
      args:
        # t2p: "/usr/local/bin/"
        lang: "C"
        workdir: ""
        username: ${USER}
      context: ./.devcontainer/
      dockerfile: Dockerfile
    volumes:
      - ./documents:/root/latex/documents
    working_dir: /root/latex