services:
  latex:
    container_name: LaTeX
    tty: true
    restart: always
    environment:
      - WORKDIR="latex"
      - VOLDIR="cvt-abc-map-elites"
    build:
      args:
        t2p: "/usr/local/bin/"
        lang: "C"
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./${VOLDIR}:/root/${WORKDIR}/documents
    working_dir: /root/${WORKDIR}